[project]
name = "khushi_erpnext"
authors = [
    { name = "TechInsights", email = "techinsight.ai@gmail.com"}
]
description = "Kushi's custom Erp "
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe~=15.0.0" # Installed and managed by bench.
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"

[deploy.dependencies.apt]
packages = [
    "ffmpeg",                   # Required for multimedia handling
    "libatk-bridge2.0-0",       # Accessibility toolkit
    "libdrm2",                  # Direct Rendering Manager
    "libxcomposite1",           # X Window System Composite extension
    "libxdamage1",              # X Damage extension
    "libxfixes3",               # X Fixes extension
    "libxrandr2",               # X RandR extension
    "libgbm1",                  # Generic Buffer Manager
    "libxkbcommon0",            # Keyboard handling
    "libatspi2.0-0",            # Assistive Technology Service Provider Interface
    "gstreamer1.0-libav",       # GStreamer multimedia framework (optional, for audio/video handling)
    "gstreamer1.0-plugins-base",# Base GStreamer plugins
    "gstreamer1.0-plugins-good" # Good GStreamer plugins
]
